#!/usr/bin/env bash

## OCRSHOT
## Simple bash script that allows you to copy-and-paste text via Optical Character Recognition

### After calling 'ocrshot', your cursor will be used to select an area of your screen to screenshot
### After this screenshot is taken, it's run through Tesseract to read the text inside it
### And that text, finally, is copied to your clipboard (ctrl+v to paste)

### Calling 'ocrshot -i' will do the same thing but also invert the colors of the screenshot before pushing it to Tesseract.
### This is best if you use a dark theme
### (A dark background with light text should be inverted to a light background with dark text for Tesseract)

#### Depends:
####  gnome-screenshot
####  xclip
####  tesseract
####  imagemagick


##### IMO, this is useful for copying-and-pasting text from videos or photos, as well as from Google Docs et al services which go through great lengths to prevent ctrl+c ctrl+v
##### Also IMO, it's most useful when tied to a quick&easy keyboard shortcut

invertcmd=

tmpfname=$(mktemp).png

while getopts i flag
do
	case "${flag}" in
		i) invertcmd="convert $tmpfname -negate $tmpfname";;
		*) ;;
	esac
done

gnome-screenshot -a -f "$tmpfname"

$invertcmd

ocroutput=$(tesseract -c page_separator='' "$tmpfname" -)

echo -n "$ocroutput" |  xclip -sel clip

rm "$tmpfname"
