.\" Manpage for ocrshot
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 1 "22 August 2024" "1.0" "ocrshot man page"
.SH NAME
ocrshot \- Copy text from images using Optical Character Recognition
.SH SYNOPSIS
ocrshot
.SH DESCRIPTION
ocrshot copies text to clipboard by screenshotting (using Optical Character Recognition)
After running the command 'ocrshot', your mouse can be used to select the portion of the screen to screenshot.
After you've made your selection, any text contained in that region will be copied to your clipboard
.SH OPTIONS
  -i
    Invert the colors of the screenshot before trying to read the text
    (This option is usually necessary if you're using a dark theme
     [light text on dark background, instead of dark text on light
     background])

Example:
  ocrshot
  ocrshot -i
.SH BUGS
No known bugs.
.SH AUTHOR
rail5 (andrew@rail5.org)
